# Generated by Django 4.0.4 on 2022-05-03 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventgamer',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventgamer',
            name='gamer',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='EventGamer',
        ),
    ]
