# Generated by Django 4.0.4 on 2022-05-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0002_remove_eventgamer_event_remove_eventgamer_gamer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(),
            preserve_default=False,
        ),
    ]
