# Generated by Django 4.0.4 on 2022-05-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0003_event_date_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(related_name='events', to='levelupapi.gamer'),
        ),
    ]
